title: John Zhen Fu Pang
position: Group Manager
affiliation: Institute of High Performance Computing, A*STAR
affiliation_link: https://www.a-star.edu.sg/ihpc
email: john_pang (at) ihpc.a-star.edu.sg
keywords: john pang, john zhen fu pang, john pang zhen fu
google_scholar: https://scholar.google.com/citations?user=mQZqPVAAAAAJ&hl=en&oi=ao
cv_link: ./assets/recent_cv.pdf
github_link: https://github.com/j-pang/
linkedin: https://www.linkedin.com/in/john-pang-8870948a/
twitter: https://twitter.com/jzpang/
avatar: ./assets/img/profile.jpeg
description: John Pang is a Research Scientist at A*STAR IHPC, where he works on optimization and control algorithms for studying smart grid technologies. 
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run_jekyll.sh
  - minimal-light.gemspec
  - CNAME
