title: John Zhen Fu Pang
position: Research Scientist
affiliation: Institute of High Performance Computing
affiliation_link: https://www.a-star.edu.sg/ihpc
email: john_pang (at) ihpc.a-star.edu
keywords: john pang, john zhen fu pang, john pang zhen fu
google_scholar: https://scholar.google.com/citations?user=mQZqPVAAAAAJ&hl=en&oi=ao
cv_link: 
github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/liuyaoyao/
twitter: https://twitter.com/YaoyaoLiu1/
avatar: .assets/img/profile.jpeg
google_analytics: UA-111540567-4
clustrmaps_link: //clustrmaps.com/globe.js?d=71dq8HjqihJEgSiwaSZovuMn_4gJE3ed9kCAdS0QjP0
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: John Pang is a Research Scientist at A*STAR IHPC, where he works on optimization and control algorithms for studying smart grid technologies. 
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run_jekyll.sh
  - minimal-light.gemspec
  - CNAME
